## ------------ ONT & TST------------ ##
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-ont-test
spec:
  generators:
    - list:
        elements:
          - appName: app1
            namespace: ont
            repoURL: "https://github.com/moosterhuis/test-app.git"
            targetRevision: HEAD
            path:
            valueFiles: "/env/values-ont.yaml"
          - appName: app1
            namespace: tst
            repoURL: "https://github.com/moosterhuis/test-app.git"
            targetRevision: HEAD
            path: "/env/values-tst.yaml"
            valueFiles: "/env/values-tst.yaml"
          - appName: app2
            namespace: ont
            repoURL: "https://github.com/moosterhuis/test-app.git"
            targetRevision: HEAD
            path:
            valueFiles: "/env/values-ont.yaml"
          - appName: app2
            namespace: tst
            repoURL: "https://github.com/moosterhuis/test-app.git"
            targetRevision: HEAD
            path: "/env/values-tst.yaml"
            valueFiles: "/env/values-tst.yaml"
  template:
    metadata:
      name: "{{appName}}-{{namespace}}"
      namespace: "{{namespace}}"
    spec:
      project: default
      source:
        repoURL: "{{repoUrl}}"
        targetRevision: "{{targetRevision}}"
        path: "{{path}}"
        helm:
          name: "{{appName}}"
          valueFiles:
            - "{{valueFiles}}"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
---
## ------------ ACC & PROD------------ ##