apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application
spec:
  generators:
    - list:
        elements:
          - namespace: test-app-ont
          - namespace: test-app-tst
  template:
    metadata:
      name: "test-app-{{namespace}}"
      namespace: "{{namespace}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/moosterhuis/test-app.git
        targetRevision: main
        path: .
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
