apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application
spec:
  generators:
    - list:
        elements:
          - namespace: ont
          - namespace: tst
  template:
    metadata:
      name: "application-{{namespace}}"
      namespace: "{{namespace}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/moosterhuis/test-app.git
        targetRevision: HEAD
        path: .
        helm:
          valueFiles:
            - "/env/values-{{namespace}}.yaml"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{namespace}}"
      syncPolicy: {}
